use super::handler_traits::{AipParams, AipOutput};
use super::registry_internal::RegistryEntry;

/// Trait for handlers that can be registered in the AIP registry.
///
/// Implementations are generated by the `#[aip_handler]` attribute macro.
/// The trait carries metadata extracted from the function and provides a method
/// to construct a `RegistryEntry` that wraps the handler closure.
///
/// Note: The trait is not intended for manual implementation outside this crate
/// at present. The macro-generated implementors live within this crate and
/// access internal types directly.
pub trait AipHandler {
	/// Marker type indicating whether the handler is synchronous or asynchronous.
	type Marker;

	/// The typed parameters type.
	type Params: AipParams;

	/// The typed output type.
	type Output: AipOutput;

	/// Optional human-readable description of the handler, typically from doc comments.
	fn handler_desc() -> Option<&'static str> {
		None
	}

	/// Optional title of the handler, e.g. extracted from the first ATX heading
	/// in the doc comments.
	fn handler_title() -> Option<&'static str> {
		None
	}

	/// Construct a [`RegistryEntry`] for the given path, wrapping the handler
	/// as a Lua closure and including all schemas and metadata.
	fn create_entry(path: &str) -> RegistryEntry;
}
