use super::handler_traits::{AipHandlerMeta, AipOutput, AipParams};
use super::registry_internal::RegistryEntry;

/// Trait for handlers that can be registered in the AIP registry.
///
/// Implementations are generated by the `#[aip_handler]` attribute macro.
/// The trait carries metadata extracted from the function and provides a method
/// to construct a `RegistryEntry` that wraps the handler closure.
///
/// Note: The trait is not intended for manual implementation outside this crate
/// at present. The macro-generated implementors live within this crate and
/// access internal types directly.
pub trait AipHandler {
	/// Marker type indicating whether the handler is synchronous or asynchronous.
	type Marker;

	/// The typed parameters type.
	type Params: AipParams;

	/// The typed output type.
	type Output: AipOutput;

	/// Returns the metadata (title and description) extracted from the handler's
	/// doc comments. The default returns empty metadata; the `#[aip_handler]`
	/// macro overrides this to provide the actual values.
	fn handler_meta() -> AipHandlerMeta {
		AipHandlerMeta {
			description: None,
			title: None,
		}
	}

	/// Construct a [`RegistryEntry`] for the given path, wrapping the handler
	/// as a Lua closure and including all schemas and metadata.
	fn create_entry(path: &str) -> RegistryEntry;
}
